# Generated by Django 4.2.1 on 2024-08-08 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoriteproductmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite_product', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='productviewmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_view', to='product.productmodel', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productviewmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_product_view', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='productvideomodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_video', to='product.productmodel', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='productpricechartmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_chart', to='product.productmodel', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='brands_products', to='product.brandmodel', verbose_name='برند'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='child_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_category_products', to='product.childcategorymodel', verbose_name='دسته بندی فرزند'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_category_products', to='product.maincategorymodel', verbose_name='دسته بندی اصلی'),
        ),
        migrations.AddField(
            model_name='productimagemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.productmodel', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='productfieldmodel',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fields', to='product.categoryfiledmodel', verbose_name='فیلد'),
        ),
        migrations.AddField(
            model_name='productfieldmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_fields', to='product.productmodel', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='productcommentpositivepointsview',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_positive_points', to='product.productcommentmodel'),
        ),
        migrations.AddField(
            model_name='productcommentnegativepointsview',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_negative_points', to='product.productcommentmodel'),
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='admin_seen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_seen_product_comments', to=settings.AUTH_USER_MODEL, verbose_name='بررسی ادمین'),
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='admin_solve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_solve_product_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='product.productmodel', verbose_name='کالا'),
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_product_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='maincategoryimagemodel',
            name='main_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_category_image', to='product.maincategorymodel', verbose_name='دسته بندی اصلی'),
        ),
        migrations.AddField(
            model_name='childcategorymodel',
            name='base_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_category_child', to='product.maincategorymodel', verbose_name='دسته بندی اصلی'),
        ),
        migrations.AddField(
            model_name='childcategorymodel',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='product.childcategorymodel', verbose_name='دسته بندی پدر'),
        ),
        migrations.AddField(
            model_name='childcategoryimagemodel',
            name='child_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_category_image', to='product.childcategorymodel', verbose_name='دسته بندی فرزند'),
        ),
        migrations.AddField(
            model_name='categoryfiledmodel',
            name='category',
            field=models.ManyToManyField(related_name='child_category_field', to='product.childcategorymodel', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='brandmodel',
            name='category',
            field=models.ManyToManyField(related_name='category_brands', to='product.childcategorymodel', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='ssdmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ssd_type', to='product.ssdtypemodel', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='rammodel',
            name='ddr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ddr_rams', to='product.ddrmodel', verbose_name='نسل رم'),
        ),
        migrations.AddField(
            model_name='rammodel',
            name='frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='frequency_rams', to='product.ramfrequencymodel', verbose_name='فرکانس'),
        ),
        migrations.AddField(
            model_name='rammodel',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='platform_rams', to='product.ramplatformmodel', verbose_name='پلتفرم'),
        ),
        migrations.AddField(
            model_name='powermodel',
            name='form_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_factor_powers', to='product.powerformfactormodel', verbose_name='فرم فاکنور'),
        ),
        migrations.AddField(
            model_name='mainboardmodel',
            name='chipset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chipset_main_boards', to='product.mainboardchipsetmodel', verbose_name='چیپست'),
        ),
        migrations.AddField(
            model_name='mainboardmodel',
            name='ddr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ddr_main_boards', to='product.ddrmodel', verbose_name='نسل رم'),
        ),
        migrations.AddField(
            model_name='mainboardmodel',
            name='form_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='form_factor_main_boards', to='product.formfactormodel', verbose_name='فرم فاکتور'),
        ),
        migrations.AddField(
            model_name='mainboardmodel',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='platform_main_boards', to='product.cpuplatformmodel', verbose_name='پلتفرم'),
        ),
        migrations.AddField(
            model_name='mainboardmodel',
            name='ram_frequency',
            field=models.ManyToManyField(related_name='ram_frequency_main_boards', to='product.ramfrequencymodel', verbose_name='فرکانس رم'),
        ),
        migrations.AddField(
            model_name='mainboardmodel',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='socket_main_boards', to='product.sockettypemodel', verbose_name='سوکت'),
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopcpumodel', verbose_name='پردازنده'),
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='gpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopgpumodel', verbose_name='گرافیک'),
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='gpu_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopgpustoragemodel', verbose_name='حافظه پردازنده گرافیکی'),
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='hard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptophardmodel', verbose_name='هارد'),
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptoprammodel', verbose_name='رم'),
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopresolutionmodel', verbose_name='رزولوشن'),
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='screen_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopscreensizemodel', verbose_name='ابعاد صفحه نمایش'),
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='ssd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.laptopssdmodel', verbose_name='اس اس دی'),
        ),
        migrations.AddField(
            model_name='hardmodel',
            name='sata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sata_hard', to='product.satatypemodel', verbose_name='ساتا'),
        ),
        migrations.AddField(
            model_name='hardmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hard_types', to='product.hardtypemodel', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='gpumodel',
            name='ddr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ddr_gpus', to='product.gpuddrmodel', verbose_name='نسل رم'),
        ),
        migrations.AddField(
            model_name='gpumodel',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='platform_gpus', to='product.gpuplatformmodel', verbose_name='پلتفرم'),
        ),
        migrations.AddField(
            model_name='fancpumodel',
            name='platform',
            field=models.ManyToManyField(related_name='platform_fan_cpus', to='product.fancpuplatformmodel', verbose_name='پلتفرم'),
        ),
        migrations.AddField(
            model_name='fancpumodel',
            name='sockets',
            field=models.ManyToManyField(related_name='socket_fan_cpus', to='product.sockettypemodel', verbose_name='سوکت'),
        ),
        migrations.AddField(
            model_name='cpumodel',
            name='bit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bit_cpus', to='product.bittypemodel', verbose_name='بیت'),
        ),
        migrations.AddField(
            model_name='cpumodel',
            name='core',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='core_cpus', to='product.cpucoremodel', verbose_name='تعداد هسته'),
        ),
        migrations.AddField(
            model_name='cpumodel',
            name='ddr',
            field=models.ManyToManyField(related_name='ddr_cpus', to='product.ddrmodel', verbose_name='نسل رم'),
        ),
        migrations.AddField(
            model_name='cpumodel',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='on_board', to='product.onboardgpumodel', verbose_name='گرافیک'),
        ),
        migrations.AddField(
            model_name='cpumodel',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='platform_cpus', to='product.cpuplatformmodel', verbose_name='پلتقرم'),
        ),
        migrations.AddField(
            model_name='cpumodel',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='series_cpus', to='product.seriesmodel', verbose_name='سری'),
        ),
        migrations.AddField(
            model_name='cpumodel',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='socket_cpus', to='product.sockettypemodel', verbose_name='سوکت'),
        ),
        migrations.AddField(
            model_name='casemodel',
            name='main_board_form_factor',
            field=models.ManyToManyField(related_name='form_factor_cases', to='product.formfactormodel', verbose_name='فرم فاکتور مادربرد'),
        ),
        migrations.AddField(
            model_name='casemodel',
            name='power_form_factor',
            field=models.ManyToManyField(related_name='power_form_cases', to='product.powerformfactormodel', verbose_name='فرم فاکتور پاور'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.casemodel', verbose_name='کیس'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='cpu',
            field=models.ManyToManyField(to='product.cpumodel', verbose_name='پردازنده'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='fan_cpu',
            field=models.ManyToManyField(to='product.fancpumodel', verbose_name='فن پردازنده'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='gpu',
            field=models.ManyToManyField(blank=True, to='product.gpumodel', verbose_name='کارت گرافیک'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='hard',
            field=models.ManyToManyField(blank=True, to='product.hardmodel', verbose_name='هارد'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='main_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_board_assembled_cases', to='product.mainboardmodel', verbose_name='مادربرد'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='optical_drive',
            field=models.ManyToManyField(blank=True, to='product.opticaldrivemodel', verbose_name='درایو نوری'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='power',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.powermodel', verbose_name='پاور'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='ram',
            field=models.ManyToManyField(to='product.rammodel', verbose_name='رم'),
        ),
        migrations.AddField(
            model_name='assembledcasemodel',
            name='ssd',
            field=models.ManyToManyField(blank=True, to='product.ssdmodel', verbose_name=''),
        ),
    ]
