# Generated by Django 5.0.6 on 2024-10-18 11:08

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='published_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
    ]
