# Generated by Django 5.0.6 on 2024-10-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productmodel_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
