# Generated by Django 5.1 on 2024-09-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productvideomodel_poster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcommentpositivepointsview',
            name='comment',
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='negative_votes',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcommentmodel',
            name='positive_votes',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductCommentNegativePointsView',
        ),
        migrations.DeleteModel(
            name='ProductCommentPositivePointsView',
        ),
    ]
