# Generated by Django 5.0.6 on 2024-10-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productmodel_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
    ]
