# Generated by Django 5.1 on 2024-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productcommentmodel_positive_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentmodel',
            name='positive_votes',
            field=models.JSONField(),
        ),
    ]
