# Generated by Django 5.0.6 on 2024-10-18 12:31

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productmodel_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='published_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='update_date',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
