# Generated by Django 5.1 on 2024-09-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productcommentmodel_positive_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentmodel',
            name='negative_votes',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='productcommentmodel',
            name='positive_votes',
            field=models.CharField(),
        ),
    ]
