# Generated by Django 5.0.6 on 2024-10-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productmodel_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='published_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
