# Generated by Django 5.1 on 2024-09-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productcommentmodel_negative_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentmodel',
            name='negative_votes',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='productcommentmodel',
            name='positive_votes',
            field=models.JSONField(),
        ),
    ]
