# Generated by Django 4.2.1 on 2024-08-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedproductsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_products', to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='instantoffermodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_instant_offer', to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='financialstatementobjectsmodel',
            name='financial_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statement_objects', to='panel.financialstatementmodel'),
        ),
    ]
