# Generated by Django 5.1 on 2024-08-28 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0002_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworksmodel',
            name='user',
            field=models.ManyToManyField(related_name='user_daily_works', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialstatementobjectsmodel',
            name='financial_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statement_objects', to='panel.financialstatementmodel'),
        ),
        migrations.AddField(
            model_name='instantoffermodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_instant_offer', to='product.productmodel'),
        ),
        migrations.AddField(
            model_name='suggestedproductsmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_products', to='product.productmodel'),
        ),
    ]
