# Generated by Django 4.2.1 on 2024-08-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
