# Generated by Django 5.0.13 on 2025-03-17 15:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutusmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutusmodel',
            name='text',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
