# Generated by Django 4.2.1 on 2024-08-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_sitedetailmodel_work_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('family_name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sitedetailmodel',
            name='about_us_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
