# Generated by Django 4.2.1 on 2024-08-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_advertisingbannermodel_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisingbannermodel',
            name='type',
        ),
        migrations.AlterField(
            model_name='advertisingbannermodel',
            name='order',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='advertisingbannermodel',
            name='url',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
