# Generated by Django 5.1 on 2024-08-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_advertisingbannermodel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
