# Generated by Django 4.2.1 on 2024-08-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='designation',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
