# Generated by Django 4.2.1 on 2024-08-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_auther',
            field=models.BooleanField(default=False),
        ),
    ]
