# Generated by Django 4.2.1 on 2024-08-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpumodel',
            name='socket',
        ),
        migrations.RemoveField(
            model_name='cpusocketmodel',
            name='brand',
        ),
        migrations.RenameField(
            model_name='mainboardmodel',
            old_name='form_factor',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='CpuBrandsModel',
        ),
        migrations.DeleteModel(
            name='CpuModel',
        ),
        migrations.DeleteModel(
            name='CpuSocketModel',
        ),
    ]
