# Generated by Django 4.2.1 on 2024-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogmodel_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
