# Generated by Django 5.0.6 on 2024-12-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoCategory',
            new_name='VideoCategoryModel',
        ),
    ]
