# Generated by Django 4.2.1 on 2024-08-08 17:08

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('type', models.CharField(choices=[('blog_comment', 'Blog Comment'), ('product_comment', 'Product Comment'), ('others', 'Others')], max_length=1000)),
                ('admin_description', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('admin_seen', models.BooleanField(default=False)),
                ('admin_seen_date', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('description', models.TextField()),
                ('published_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('expire_date', django_jalali.db.models.jDateTimeField()),
            ],
        ),
    ]
