# Generated by Django 5.1 on 2024-09-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        ('notification', '0002_initial'),
        ('product', '0004_remove_productcommentpositivepointsview_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotificationmodel',
            name='blog_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment_admin_notification', to='blog.blogcommentmodel'),
        ),
        migrations.AlterField(
            model_name='adminnotificationmodel',
            name='product_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_comment_admin_notification', to='product.productcommentmodel'),
        ),
    ]
