# Generated by Django 5.1 on 2024-08-28 09:37

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('last_text', models.TextField(blank=True, null=True)),
                ('admin', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('replay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_replays', to='chat.userchatmodel')),
            ],
        ),
    ]
