# Generated by Django 5.1 on 2024-08-28 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchatroommodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchatmodel',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_chats', to='chat.userchatroommodel'),
        ),
    ]
