# Generated by Django 4.2.1 on 2024-08-08 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatroommodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userchatmodel',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_chats', to='chat.userchatroommodel'),
        ),
        migrations.AddField(
            model_name='userchatmodel',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_replays', to='chat.userchatmodel'),
        ),
        migrations.AddField(
            model_name='userchatmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
