# Generated by Django 4.2.1 on 2024-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/file'),
        ),
    ]
