# Generated by Django 4.2.1 on 2024-09-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userchatroommodel_ip_alter_userchatroommodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatmodel',
            name='ip',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userchatroommodel',
            name='ip',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
