# Generated by Django 4.2.1 on 2024-09-13 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_userchatmodel_ip_alter_userchatroommodel_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchatroommodel',
            name='admin',
        ),
        migrations.AddField(
            model_name='userchatmodel',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userchatmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
